# Generated by Django 4.2.7 on 2024-04-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='sizes',
        ),
        migrations.CreateModel(
            name='ClothesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_sizes', to='store.clothes')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size')),
            ],
        ),
    ]
