# Generated by Django 4.2.7 on 2024-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_clothes_sizes_clothessize'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='sizes',
            field=models.ManyToManyField(through='store.ClothesSize', to='store.size'),
        ),
    ]
