# Generated by Django 4.2.7 on 2024-04-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='count',
        ),
    ]
