# Generated by Django 4.2.7 on 2024-04-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cartitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='cartItem_quantity',
        ),
    ]
