# Generated by Django 4.2.7 on 2024-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_image_alter_clothes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='image',
        ),
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ManyToManyField(null=True, to='store.image'),
        ),
    ]
