# Generated by Django 4.2.7 on 2024-04-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_clothes_image_clothes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='image',
            new_name='images',
        ),
    ]
