# Generated by Django 4.2.7 on 2024-04-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_image_clothes_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='images',
            field=models.ManyToManyField(to='store.image'),
        ),
    ]
